# SUM26001 Final Project Report Expectations

This final report is the "paper" of this course, which will take 60% of students' final grade.

The report should be submitted as a GitHub repository link, through the class's website: [https://classproject-iss-bfsu.azurewebsites.net/report/](https://classproject-iss-bfsu.azurewebsites.net/report/)


# Required components of the GitHub repository:

## 1. A `README.md` file that contains the following information:

- Description of the project, including the problem statement, objectives, and progress made / lessons learned.
- List of member names, student IDs, and each member's contribution to the project.
- A link to the final report pdf placed in the repo. And a link to the qmd file which generated this pdf. 


## 2. In the root directory of the repo, include a `.gitignore` file that contains at least the following lines:

```
# Quarto preview/render artifacts
*_files/
*_cache/
.quarto/
.quarto_preview/
_freeze/

*.csv
*.docx

# Temporary notebook intermediates generated by Quarto/Jupyter
*.quarto_ipynb
*.quarto_ipynb_*

```

## 3. Final report needs to be included in the repo as a pdf file, and include qmd file which generates this pdf.


# Evaluation criteria (total 60 points):


1. Clearly state the problem to be solved (5 points)

2. Present the results clearly or document efforts to address the bottlenecks (30 points)

3. Demonstrate collaborations through git commit/merge history (5 points)

4. Good story telling (5 points)

5. Proper format (qmd, pdf, `README.md`, and `.gitignore`) (15 points)

Regarding item 2, if your project moves smoothly, just write out your progress and result. But if you run into some bottlenecks that prevent you from getting results, you need to write down the challenges you face and how you accommodate them. In the following way:


For each of the bottlenecks you encounter, please write down the following:

- Core challenges we face (the goal you try to achieve):
- Where/How we got stuck (what stops you from achieving the goal): 
- Changes we made to accommodate the bottleneck (e.g., change the goal, change the method, change the data, etc.):
 
If in the end you solve the bottleneck, please also add the following:

- Solutions we found:


### Report submission deadline: 11:59 PM, July 25th (Beijing Time)